In [204]:
import pandas as pd
df = pd.read_csv('intern_task.csv', header=0)

In [205]:
df.head()

,rank,query_id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_134,feature_135,feature_136,feature_137,feature_138,feature_139,feature_140,feature_141,feature_142,feature_143
0,0,10,1.0,0.0,1.0,3.0,3.0,0.333333,0.0,0.333333,...,0.0,0.000000,0.454545,0.890238,8.655534,1.000000,0.077778,0.002222,1.0,0.333333
1,1,10,3.0,0.0,3.0,0.0,3.0,1.000000,0.0,1.000000,...,0.0,0.000000,0.000000,0.773976,23.130514,0.000000,0.027826,0.000430,44.0,14.666667
2,0,10,3.0,0.0,2.0,0.0,3.0,1.000000,0.0,0.666667,...,0.0,0.000000,0.000000,0.918308,13.351339,0.000000,0.014925,0.000104,22.0,7.333333
3,1,10,3.0,0.0,3.0,0.0,3.0,1.000000,0.0,1.000000,...,0.0,0.000000,0.000000,0.975355,18.240926,0.000000,0.053140,0.000255,8.0,2.666667
4,2,10,3.0,0.0,3.0,1.0,3.0,1.000000,0.0,1.000000,...,273.0,79.670665,0.200000,0.990119,31.786048,0.333333,0.046512,0.000307,24.0,8.000000

In [206]:
unique_count = df['rank'].nunique()
print("Количество уникальных значений:", unique_count)

Количество уникальных значений: 5

In [207]:
unique_count = df['query_id'].nunique()
print("Количество уникальных значений:", unique_count)

Количество уникальных значений: 2000

In [208]:
null_check = df.isnull().any()
print("Наличие отсутствующих значений в столбцах:")
print(null_check)

Наличие отсутствующих значений в столбцах:
rank           False
query_id       False
feature_0      False
feature_1      False
feature_2      False
               ...
feature_139    False
feature_140    False
feature_141    False
feature_142    False
feature_143    False
Length: 146, dtype: bool

In [209]:
# обучаем модель ранжированию внутри сессии, где query_id= 10
data = df[df['query_id'] == 10]

In [210]:
data.drop('query_id', axis=1, inplace=True)
data

/tmp/ipykernel_9449/2628678927.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('query_id', axis=1, inplace=True)

,rank,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,...,feature_134,feature_135,feature_136,feature_137,feature_138,feature_139,feature_140,feature_141,feature_142,feature_143
0,0,1.0,0.0,1.0,3.0,3.0,0.333333,0.0,0.333333,0.000000,...,0.0,0.000000,0.454545,0.890238,8.655534,1.000000,0.077778,0.002222,1.0,0.333333
1,1,3.0,0.0,3.0,0.0,3.0,1.000000,0.0,1.000000,0.004251,...,0.0,0.000000,0.000000,0.773976,23.130514,0.000000,0.027826,0.000430,44.0,14.666667
2,0,3.0,0.0,2.0,0.0,3.0,1.000000,0.0,0.666667,0.008501,...,0.0,0.000000,0.000000,0.918308,13.351339,0.000000,0.014925,0.000104,22.0,7.333333
3,1,3.0,0.0,3.0,0.0,3.0,1.000000,0.0,1.000000,0.012752,...,0.0,0.000000,0.000000,0.975355,18.240926,0.000000,0.053140,0.000255,8.0,2.666667
4,2,3.0,0.0,3.0,1.0,3.0,1.000000,0.0,1.000000,0.017003,...,273.0,79.670665,0.200000,0.990119,31.786048,0.333333,0.046512,0.000307,24.0,8.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.369808,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
88,0,2.0,0.0,0.0,0.0,2.0,0.666667,0.0,0.000000,0.374059,...,0.0,0.000000,0.000000,0.427823,0.000000,0.000000,0.004297,0.000025,7.0,2.333333
89,1,2.0,0.0,2.0,1.0,2.0,0.666667,0.0,0.666667,0.378310,...,0.0,0.000000,0.166667,0.907969,13.545122,0.333333,0.019259,0.000180,10.0,3.333333
90,1,3.0,3.0,3.0,1.0,3.0,1.000000,1.0,1.000000,0.382560,...,1.0,1.800000,0.125000,0.989621,18.240926,0.333333,0.007376,0.000001,14.0,4.666667
91,0,3.0,0.0,3.0,1.0,3.0,1.000000,0.0,1.000000,0.386811,...,0.0,0.000000,0.125000,0.975355,18.240926,0.333333,0.020101,0.000026,8.0,2.666667

In [211]:
size = df.shape
size

(235258, 146)

In [212]:
size = data.shape
size

(92, 145)

In [181]:
y = data['rank']#у- ранк

In [187]:
y

0     0
1     1
2     0
3     1
4     2
     ..
87    1
88    0
89    1
90    1
91    0
Name: rank, Length: 92, dtype: int64

In [183]:
data.drop('rank', axis=1, inplace=True)

/tmp/ipykernel_9449/799740295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('rank', axis=1, inplace=True)

In [213]:
X = data.values#векторы фичей

In [214]:
import numpy as np
num_classes = 5
from keras.utils import to_categorical

In [215]:
y_one_hot =pd.get_dummies(y)
print(y_one_hot)

        0      1      2      3      4
0    True  False  False  False  False
1   False   True  False  False  False
2    True  False  False  False  False
3   False   True  False  False  False
4   False  False   True  False  False
..    ...    ...    ...    ...    ...
87  False   True  False  False  False
88   True  False  False  False  False
89  False   True  False  False  False
90  False   True  False  False  False
91   True  False  False  False  False

[92 rows x 5 columns]

In [216]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.3, random_state=42)

In [224]:
import tensorflow as tf
from tensorflow.keras import layers, models

input_dim = X_train.shape[1]  # Получаем количество признаков из обучающих данных

# Создание модели нейронной сети
model = models.Sequential([
    layers.Dense(128, activation='relu', input_shape=(input_dim,)),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(5, activation='softmax')  
])

# Компиляция модели
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Обучение модели
history = model.fit(X_train, y_train, epochs=30, batch_size=32, validation_split=0.2)
scores = model.predict(X_test)
# Оценка модели на тестовых данных
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)

Epoch 1/30

/home/anastasiia/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 187ms/step - accuracy: 0.7206 - loss: 390.0935 - val_accuracy: 0.3077 - val_loss: 532.3550
Epoch 2/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4387 - loss: 227.9418 - val_accuracy: 0.3846 - val_loss: 378.5746
Epoch 3/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5431 - loss: 209.0776 - val_accuracy: 0.5385 - val_loss: 265.5146
Epoch 4/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4726 - loss: 171.1986 - val_accuracy: 0.3846 - val_loss: 190.1653
Epoch 5/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4700 - loss: 120.1011 - val_accuracy: 0.6154 - val_loss: 180.6568
Epoch 6/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5770 - loss: 71.8961 - val_accuracy: 0.4615 - val_loss: 147.3849
Epoch 7/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5770 - loss: 48.4012 - val_accuracy: 0.4615 - val_loss: 151.4893
Epoch 8/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4830 - loss: 59.6289 - val_accuracy: 0.3077 - val_loss: 166.2337
Epoch 9/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4491 - loss: 55.9040 - val_accuracy: 0.3077 - val_loss: 188.3491
Epoch 10/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5039 - loss: 59.8550 - val_accuracy: 0.5385 - val_loss: 116.3356
Epoch 11/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6266 - loss: 35.9612 - val_accuracy: 0.3846 - val_loss: 107.7519
Epoch 12/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6136 - loss: 44.9041 - val_accuracy: 0.3077 - val_loss: 59.5626
Epoch 13/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5378 - loss: 17.0193 - val_accuracy: 0.3077 - val_loss: 40.0440
Epoch 14/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4361 - loss: 19.0682 - val_accuracy: 0.3846 - val_loss: 29.7005
Epoch 15/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5378 - loss: 15.4875 - val_accuracy: 0.3846 - val_loss: 28.8544
Epoch 16/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5797 - loss: 20.4440 - val_accuracy: 0.4615 - val_loss: 20.5428
Epoch 17/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6213 - loss: 17.2407 - val_accuracy: 0.3077 - val_loss: 22.1940
Epoch 18/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4804 - loss: 11.7661 - val_accuracy: 0.0769 - val_loss: 24.9192
Epoch 19/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3838 - loss: 18.7578 - val_accuracy: 0.4615 - val_loss: 27.6003
Epoch 20/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5874 - loss: 16.8030 - val_accuracy: 0.5385 - val_loss: 43.7203
Epoch 21/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5901 - loss: 18.5204 - val_accuracy: 0.5385 - val_loss: 30.3244
Epoch 22/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6109 - loss: 10.3373 - val_accuracy: 0.3077 - val_loss: 41.6229
Epoch 23/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6162 - loss: 12.2471 - val_accuracy: 0.3077 - val_loss: 41.7041
Epoch 24/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5613 - loss: 8.9389 - val_accuracy: 0.3846 - val_loss: 51.3543
Epoch 25/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4726 - loss: 12.3788 - val_accuracy: 0.3846 - val_loss: 53.7735
Epoch 26/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6058 - loss: 10.6124 - val_accuracy: 0.3846 - val_loss: 48.2061
Epoch 27/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7232 - loss: 6.6850 - val_accuracy: 0.3846 - val_loss: 55.2568
Epoch 28/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6554 - loss: 9.0793 - val_accuracy: 0.2308 - val_loss: 48.0519
Epoch 29/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6683 - loss: 8.0346 - val_accuracy: 0.4615 - val_loss: 64.8753
Epoch 30/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5639 - loss: 18.0836 - val_accuracy: 0.4615 - val_loss: 50.3918
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4643 - loss: 35.4940
Test accuracy: 0.4642857015132904

In [225]:
from sklearn.metrics import ndcg_score

ndcg_score(y_test, scores)
#подсчет метрики ранжирования

0.7485832745810728